mypro/library/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
app_name="books"


urlpatterns = [

    path('',views.home,name="home"),
    path('add',views.add,name="add"),
    path('view',views.view,name="views"),

]

mypro/library/library/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('students/',include('students.urls')),

]

mypro/library/students/urls.py
from django.contrib import admin
from django.urls import path
from students import views
app_name="students"


urlpatterns = [

    path('rgr',views.rgr,name="rgr"),
    path('log',views.log,name="log"),

]

mypro/library/books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title=models.CharField(max_length=20)
    author= models.CharField(max_length=20)
    price=models.IntegerField()

    def __str__(self):
        return self.title

mypro/library/students/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()

mypro/library/books/views.py
from django.shortcuts import render
from books.models import Book

# Create your views here.
#function based:
def home(request):

    return render(request, 'home.html')

def add(request):


    if(request.method=="POST"):
        t=request.POST['t']
        a = request.POST['a']
        p= request.POST['p']
        b=Book.objects.create(title=t,auhtor=a,price=p)
        b.save()
        return viewbook(request)
    return render(request, 'addbooks.html')

def view(request):
    k=Book.objects.all()

    return render(request, 'viewbooks.html',{'b':k})

mypro/library/students/views.py
from django.shortcuts import render

# Create your views here.
#function based:

def rgr(request):
    return render(request,'register.html')

def log(request):
    return render(request,'login.html')

mypro/library/templates/addbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h2>Add</h2>
<center>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" placeholder="enter the title">
</div>
<div class="mb-3">
  <label class="form-label">Author</label>
  <input type="text" class="form-control" name="a" placeholder="enter the author">
</div>
<div class="mb-3">
  <label class="form-label">Price</label>
  <input type="number" class="form-control" name="p" placeholder="enter the price">
</div>
    <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
</div>


    </form>
    </center>
{% endblock %}

mypro/library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Libraryapp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'books:add' %}">Addbooks</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'books:views' %}">Viewbooks</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'students:rgr' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'students:log' %}">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


</body>
</html>

mypro/library/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}



<h1>Home Page</h1>
{% endblock %}
<h1>Library app</h1>
<a href="{% url 'books:home' %}">Link to Home Page</a><br>
<a href="{% url 'books:add' %}">Link to Addbooks Page</a><br>
<a href="{% url 'books:views' %}">Link to Viewbooks Page</a><br>
<a href="{% url 'students:rgr' %}">Link to Register Page</a><br>
<a href="{% url 'students:log' %}">Link to Login Page</a><br>

mypro/library/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h2>Hello Java</h2>
{% endblock %}

mypro/library/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h2>Hello</h2>
{% endblock %}

mypro/library/templates/viewbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h2>View books</h2>

<table>
    <tr>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
    </tr>
    {% for i in b %}
    <tr>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.price}}</td>

    </tr>
    {% endfor %}
</table>
<!--<ol>-->
<!--    {% for i in b %}-->
<!--    <li>Book Details</li>-->
<!--    <ul>-->
<!--        <li>TITLE:{{i.title}}</li>-->
<!--    </ul>-->
<!--    <li>Book Details</li>-->
<!--    {% endfor %}-->
<!--</ol>-->