ecommerce/cart/urls.py
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<n>',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
    path('cart_trash/<n>',views.cart_trash,name="cart_trash"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),



]


if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.urls import path
from search import views
app_name="search"
urlpatterns = [


    path('',views.search,name="search"),

]

ecommerce/shop/urls.py
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name="cate"),
    path('product/<p>',views.product,name="product"),
    path('details/<c>',views.details,name="details"),
    path('register',views.register,name="reg"),
    path('login', views.user_login, name="log"),
    path('logout',views.user_logout,name="logout"),


]

ecommerce/cart/models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Product
from django.http import HttpResponse


# Create your models here.

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    ordered_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to='category',null=True,blank=True)
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()
    image = models.ImageField(upload_to='product', null=True, blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart,Account,Order
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


# Create your views here.
@login_required
def cartview(request):
    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
           total+=i.quantity*i.product.price
    except:
        pass
    return render(request,'cartview.html',{'c':cart,'total':total})
@login_required
def addtocart(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock > 0):
           cart.quantity+=1
           cart.save()
           p.stock-=1
           p.save()
    except:
        if(p.stock > 0):
           cart=Cart.objects.create(product=p,user=u,quantity=1)
           cart.save()
           p.stock-=1
           p.save()
    return cartview(request)


@login_required
def cart_remove(request,n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity>1):
            cart.quantity-=1
            cart.save()
            p.stock+=1
            p.save()

        else:
            cart.delete()
            p.stock+=1
            p.save()
    except:
        pass
    return cartview(request)
@login_required
def cart_trash(request,n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock +=cart.quantity
        p.save()
    except:
        pass
    return cartview(request)
@login_required
def orderform(request):
    if (request.method == "POST"):
        a= request.POST['a']
        p= request.POST['p']
        n= request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)
        total=0
        for i in cart:
            total+=i.quantity*i.product.price
            try:
                num=n
                ac=Account.objects.get(acctnum=num)
                if(ac.amount>=total):
                    ac.amount=ac.amount-total
                    ac.save()
                    for i in cart:
                        o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                        o.save()
                    cart.delete()
                    mag="your order placed successfully"
                    return render(request,'orderdetail.html',{'msg':msg})
                else:
                    msg="Insufficient balance.you can't place order"
                    return render(request,'orderdetail.html',{'msg':msg})
            except:
                pass
    return render(request,'orderform.html')
@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)



    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.
def search(request):
    b=None
    q=""
    if(request.method=="POST"):
           q= request.POST['q']
           if q:
              b=Product.objects.filter(Q(name__icontains=q)| Q(desc__icontains=q))
    return render(request,'search.html',{'q':q,'b':b})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
# Create your views here.

def allcategories(request):
    m = Category.objects.all()
    return render(request,'category.html',{'m':m})

def product(request,p):

    m=Category.objects.get(name=p)
    p=Product.objects.filter(category=m)
    return render(request,'product.html',{'m':m,'p':p})

def details(request,c):
    p= Product.objects.get(name=c)
    return render(request,'details.html',{'p':p})


def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        # o=request.POST['o']
        # a=request.POST['a']
        if(p==cp):
            user=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            user.save()
            return redirect('shop:cate')
        else:
            return HttpResponse("Password are not same")
    return render(request,'register.html')


def user_login(request):
    if(request.method=="POST"):
        r=request.POST['r']
        w=request.POST['w']
        user=authenticate(username=r,password=w)
        if user:
            login(request,user)
            return redirect('shop:cate')
        else:
            return HttpResponse("Invalid credentials")

    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)

    return redirect('shop:log')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300&family=Manrope:wght@200;300&family=Merriweather:wght@700&family=Mukta:wght@200&family=Roboto:wght@100&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>

<header>
    <center>
    <img src="{% static 'images/logo3.jpg' %}" height="100px" width="100px">
</center>
</header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mt-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MYSHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link fw-bold" aria-current="page" href="{% url 'shop:cate' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <b>All categories</b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:product' i.name %}">{{i.name}}</a></li>

            {% endfor %}
          </ul>


        {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:logout' %}">Logout</a>
        </li>
        {% if user.is_superuser == False %}
        <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup class="">{{count}}</sup></a>
        </li>
        <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
        {% endif %}
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:reg' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:log' %}">Login</a>
        </li>
        {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
        {% csrf_token %}
        <input class="form-control me-1" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-danger" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}

{% endblock %}
<footer class="footer">
<div>
  <p><b><i class="fa-solid fa-copyright"></i> Myshop Pvt Ltd. Allrights Reserved.</b></p>
  </div>
</footer>
</body>
</html>

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
<div class="row fs-4 text-center">
    <h4 class="text-center">Shopping Cart</h4>
    <div class="col-7"><table class="table table-bordered"><tr><th colspan="2">Cart Items</th></tr>
    {% for i in c %}
        <tr>
            <td>
                <img src="{{i.product.image.url}}" height="150px" width="150px">
            </td>
            <td>
                <h6>{{i.product.name}}</h6>
            </td>
            <td>
                <h6>Product Id:{{i.product.id}}</h6>
                <h6>Unit Price:{{i.product.price}}</h6>
                <h6>Quantity:{{i.quantity}}*{{i.product.price}}</h6></td>
            <td>Subtotal:{{i.subtotal}}</td>
            <td>
                {% if i.product.stock > 0 %}
                <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-secondary fs-5"></i></a>
            <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-secondary fs-5"></i></a>
            <a href="{% url 'cart:cart_trash' i.product.name %}"><i class="fa-solid fa-trash text-secondary fs-5"></i></a>
        {% else %}
                <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus fs-5"></i></a>
                <a href="{% url 'cart:cart_trash' i.product.name %}"><i class="fa-solid fa-trash fs-5"></i></a></td></tr>
        {% endif %}
        {% endfor %}


    </table></div>
    <div class="col-4" style="position:relative;">
        <table class="table table-bordered">
            <tr><th colspan="6">Check Out</th></tr>
    <tr><td>TOTAL:{{total}}</td></tr></table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-danger" style="position:absolute;left:10px;">Place Order</a>
        <a href="{% url 'shop:cate' %}" class="btn btn-danger" style="position:absolute;right:10px;">Continue Shopping</a>
    </div>

</div>
</div>

{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banner2.jpg' %}" height="450px" width="100%">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">Our Collections</h3>
    <p style="text-align:justify; line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

</div>
<div class="container-fluid" style="margin-bottom:100px;">
<div class="row">
{% for i in m %}
  <div class="col-sm-4">
<div class="card" style="width:30rem; ml-2">
  <img src="{{i.image.url}}" class="card-img-top" height="310px" width="100%" alt="...">
  <center>
  <div class="card-body">
    <h3 class="card-title fw-bold">{{i.name}}</h3>
<!--    <p class="card-text">{{i.desc}}</p>-->
    <a href="{% url 'shop:product' i.name %}" class="btn btn-danger">Products</a>
  </div>
    </center>
</div>
     </div>
{% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
    <div class="col-sm-4 me-5">
        <img src="{{p.image.url}}" height="400px" width="450px">
    </div>
    <div class="col-sm-6 me-5">
           <h3>{{p.name}}</h3>
            <p class="mt-4 h5 lh-base" style="text-align:justify">{{p.desc}}</p>
        <h3 class="mt-3">{{p.price}}</h3>
        <h5 class="mt-3">{{p.stock}}</h5>
        {% if user.is_superuser == True %}
        {% if p.stock == 0 %}
        <h2>Out Of Stock</h2>
        <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">Add Stock</a>
        {% else %}
        <h2>Product In Stock</h2>
        <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">Add Stock</a>
        {% endif %}

        {% else %}
        {% if p.stock == 0 %}
        <h2>Out Of Stock</h2>
        {% else %}

        <a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger mt-5">Add to Cart</a>
        {% endif %}
{% endif %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
     <div class="container" style="margin-bottom:100px;">
    <form method="POST">
        {% csrf_token %}
<h1>Login</h1>
        <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="r" placeholder="Enter the name">
</div>
        <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="w" placeholder="Enter the password">
</div>
        <div class="mb-3">

  <input type="submit" class="form-control btn btn-danger" name="g" value="Login">
</div>
        </form>
     </div>
    </center>
{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <h3 class="text-center text-danger">{{msg}}</h3>
    <h3 class="text-center text-success">Thank You</h3>
    <h3 class="text-center"><a href="{% url 'shop:cate' %}">Continue Shopping</a></h3>
</div>


{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="container" style="margin-bottom:100px;">
<h1>Orderform</h1>

        <form method="POST">
            {% csrf_token %}

<div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter your address">
</div>
            <div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="text" class="form-control" name="p" placeholder="Enter phone">
</div>
            <div class="mb-3">
  <label class="form-label">Accountnumber</label>
  <input type="number" class="form-control" name="n" placeholder="Enter your accountnumber">
</div>

        <button class="btn btn-danger" type="submit">Submit</button>
        </form>
    </div>
</center>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <h4 class="text-danger">Name of the Customer:{{u}}</h4>
        {% for i in o %}
        <div class="col-sm-4 mb-3" style="margin-left:100px;">
            <img src="{{i.product.image.url}}" height="200px" width="200px">

        </div>
        <div class="col-sm-6 mt-3 text-center">
            <b>Product Name:{{i.product.name}}</b><br>
            <b>Product Price:{{i.product.price}}</b><br>
            <b>Delivery_address:{{i.address}}</b><br>
            <b>Customer Phone:{{i.phone}}</b><br>
            <b>Ordered on:{{i.ordered_date}}</b><br>
            <b class="text-success">Delivery_status:{{i.delivery_status}}</b><br>


        </div>
        {% endfor %}

    </div>

</div>

{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        <div>
            <img src="{{m.image.url}}" height="380px" width="100%">
        </div>

        <div class="container-fluid mt-3" style="margin-bottom:100px;">
           <h3 class="text-center fw-bold">{{m.name}}</h3>
            <p style="text-align:justify; line-height:2;">{{m.desc}}</p>
        </div>
<div class="container-fluid" style="margin-bottom:100px;">
<div class="row">
{% for i in p %}
  <div class="col-sm-6">
<div class="card" style="width:45rem; ml-5">
  <img src="{{i.image.url}}" class="card-img-top" height="310px" width="100%" alt="...">
  <center>
  <div class="card-body">
    <h3 class="card-title fw-bold">{{i.name}}</h3>
<!--    <p class="card-text">{{i.desc}}</p>-->
      <h5 class="card-title fw-bold">{{i.price}}</h5>
    <a href="{% url 'shop:details' i.name %}" class="btn btn-danger">Details</a>
  </div>
    </center>
</div>
     </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="container" style="margin-bottom:100px;">
<h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the name">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>
<div class="mb-3">
  <label class="form-label">Confirm password</label>
  <input type="password" class="form-control" name="cp" placeholder="Re-enter password">
</div>
<div class="mb-3">
  <label class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter the mail">
</div>
<!--        <div class="mb-3">-->
<!--  <label class="form-label">Phone</label>-->
<!--  <input type="number" class="form-control" name="o" placeholder="Enter the phone">-->
<!--</div>-->
<!--        <div class="mb-3">-->
<!--  <label class="form-label">Place</label>-->
<!--  <input type="text" class="form-control" name="a" placeholder="Enter the place">-->
<!--</div>-->
<div class="mb-3">
  <label class="form-label">First name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter first name">
</div>
<div class="mb-3">
  <label class="form-label">Last name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter last name">
</div>
    <div class="mb-3">

  <input type="submit" name="s" class="form-control btn btn-danger">
</div>
        </form>
    </div>
    </center>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3>Product Details(search)</h3>
    <h5>You have searched query{{q}}</h5>
    {% if b %}
    <div class="container-fluid" style="margin-bottom:100px;">
<div class="row">
{% for i in b %}
  <div class="col-sm-6">
<div class="card" style="width:30rem; ml-5">
  <img src="{{i.image.url}}" class="card-img-top" height="310px" width="100%" alt="...">
  <center>
  <div class="card-body">
    <h3 class="card-title fw-bold">{{i.name}}</h3>
<!--    <p class="card-text">{{i.desc}}</p>-->
      <h5 class="card-title fw-bold">{{i.price}}</h5>
    <a href="{% url 'shop:details' i.name %}" class="btn btn-danger">Details</a>
  </div>
    </center>
</div>
     </div>
    {% endfor %}
    </div>
</div>
    {% else %}
    <b><p>No results found</p></b>
    {% endif %}

    </center>
{% endblock %}